Universe = vanilla
Notification = Complete
#Executable = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Macros/ProcessFile
Executable = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Macros/DoMixing
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Macros
accounting_group = group_atlas.boulder
request_memory   = 3 GB

#sysFlags = false none


Arguments = true MCAnalysis/Hijing/CombinedTrees/Combined_iCent$(iCent).root MixingAnalysis/Hijing/CombinedTrees/Combined_iCent$(iCent).root MixedEvents/HijingOverlay/Combined_iCent$(iCent).root
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/Hijing_Combined_Mixing_iCent$(iCent).err
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/Hijing_Combined_Mixing_iCent$(iCent).log
Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/Hijing_Combined_Mixing_iCent$(iCent).out
Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78)


#Arguments = hijing_mixing Hijing/CombinedTrees/Combined_iCent$(iCent).root Hijing/CombinedTrees/Combined_iCent$(iCent).root Hijing/Histograms/Combined_iCent$(iCent)_mixedHists.root HijingOverlay/Combined_iCent$(iCent).root true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/Hijing_Combined_Mixing_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/Hijing_Combined_Mixing_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/Hijing_Combined_Mixing_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80)


#Arguments = hijing_mixing Hijing/CombinedTrees/pp_all.root Hijing/CombinedTrees/pp_all.root Hijing/Histograms/pp_all_mixedHists.root Pythia/pp_all.root false $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/Hijing_Mixing_pp_all.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/Hijing_Mixing_pp_all.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/Hijing_Mixing_pp_all.out
#Queue 1
