Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Macros/ProcessFile.exe
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Macros
accounting_group = group_atlas.boulder
request_memory   = 8 GB

sysFlags = false none


Arguments = mcminbias CombinedTrees/pp_all.root pp_all.root MixedHistograms/pp_all_hists.root Pythia/pp_all.root false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/pp_all.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/pp_all.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/pp_all.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent1.root GroupD/GroupD_iCent1.root MixedHistograms/GroupD_iCent1_hists.root DataOverlay/GroupD/GroupD_iCent1.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent1.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent1.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent1.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent2.root GroupD/GroupD_iCent2.root MixedHistograms/GroupD_iCent2_hists.root DataOverlay/GroupD/GroupD_iCent2.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent2.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent2.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent2.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent3.root GroupD/GroupD_iCent3.root MixedHistograms/GroupD_iCent3_hists.root DataOverlay/GroupD/GroupD_iCent3.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent3.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent3.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent3.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent4.root GroupD/GroupD_iCent4.root MixedHistograms/GroupD_iCent4_hists.root DataOverlay/GroupD/GroupD_iCent4.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent4.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent4.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent4.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent5.root GroupD/GroupD_iCent5.root MixedHistograms/GroupD_iCent5_hists.root DataOverlay/GroupD/GroupD_iCent5.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent5.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent5.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent5.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent6.root GroupD/GroupD_iCent6.root MixedHistograms/GroupD_iCent6_hists.root DataOverlay/GroupD/GroupD_iCent6.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent6.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent6.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent6.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent7.root GroupD/GroupD_iCent7.root MixedHistograms/GroupD_iCent7_hists.root DataOverlay/GroupD/GroupD_iCent7.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent7.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent7.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent7.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent8.root GroupD/GroupD_iCent8.root MixedHistograms/GroupD_iCent8_hists.root DataOverlay/GroupD/GroupD_iCent8.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent8.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent8.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent8.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent9.root GroupD/GroupD_iCent9.root MixedHistograms/GroupD_iCent9_hists.root DataOverlay/GroupD/GroupD_iCent9.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent9.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent9.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent9.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent10.root GroupD/GroupD_iCent10.root MixedHistograms/GroupD_iCent10_hists.root DataOverlay/GroupD/GroupD_iCent10.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent10.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent10.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent10.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent11.root GroupD/GroupD_iCent11.root MixedHistograms/GroupD_iCent11_hists.root DataOverlay/GroupD/GroupD_iCent11.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent11.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent11.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent11.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent12.root GroupD/GroupD_iCent12.root MixedHistograms/GroupD_iCent12_hists.root DataOverlay/GroupD/GroupD_iCent12.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent12.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent12.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent12.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent13.root GroupD/GroupD_iCent13.root MixedHistograms/GroupD_iCent13_hists.root DataOverlay/GroupD/GroupD_iCent13.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent13.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent13.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent13.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent14.root GroupD/GroupD_iCent14.root MixedHistograms/GroupD_iCent14_hists.root DataOverlay/GroupD/GroupD_iCent14.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent14.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent14.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent14.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent15.root GroupD/GroupD_iCent15.root MixedHistograms/GroupD_iCent15_hists.root DataOverlay/GroupD/GroupD_iCent15.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent15.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent15.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent15.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent16.root GroupD/GroupD_iCent16.root MixedHistograms/GroupD_iCent16_hists.root DataOverlay/GroupD/GroupD_iCent16.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent16.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent16.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent16.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent17.root GroupD/GroupD_iCent17.root MixedHistograms/GroupD_iCent17_hists.root DataOverlay/GroupD/GroupD_iCent17.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent17.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent17.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent17.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent18.root GroupD/GroupD_iCent18.root MixedHistograms/GroupD_iCent18_hists.root DataOverlay/GroupD/GroupD_iCent18.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent18.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent18.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent18.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent19.root GroupD/GroupD_iCent19.root MixedHistograms/GroupD_iCent19_hists.root DataOverlay/GroupD/GroupD_iCent19.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent19.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent19.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent19.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent20.root GroupD/GroupD_iCent20.root MixedHistograms/GroupD_iCent20_hists.root DataOverlay/GroupD/GroupD_iCent20.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent20.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent20.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent20.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent21.root GroupD/GroupD_iCent21.root MixedHistograms/GroupD_iCent21_hists.root DataOverlay/GroupD/GroupD_iCent21.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent21.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent21.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent21.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent22.root GroupD/GroupD_iCent22.root MixedHistograms/GroupD_iCent22_hists.root DataOverlay/GroupD/GroupD_iCent22.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent22.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent22.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent22.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent23.root GroupD/GroupD_iCent23.root MixedHistograms/GroupD_iCent23_hists.root DataOverlay/GroupD/GroupD_iCent23.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent23.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent23.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent23.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent24.root GroupD/GroupD_iCent24.root MixedHistograms/GroupD_iCent24_hists.root DataOverlay/GroupD/GroupD_iCent24.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent24.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent25.root GroupD/GroupD_iCent25.root MixedHistograms/GroupD_iCent25_hists.root DataOverlay/GroupD/GroupD_iCent25.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent25.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent26.root GroupD/GroupD_iCent26.root MixedHistograms/GroupD_iCent26_hists.root DataOverlay/GroupD/GroupD_iCent26.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent26.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent26.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent26.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent27.root GroupD/GroupD_iCent27.root MixedHistograms/GroupD_iCent27_hists.root DataOverlay/GroupD/GroupD_iCent27.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent27.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent27.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent27.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupD_iCent28.root GroupD/GroupD_iCent28.root MixedHistograms/GroupD_iCent28_hists.root DataOverlay/GroupD/GroupD_iCent28.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupD_iCent28.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupD_iCent28.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupD_iCent28.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent1.root GroupE/GroupE_iCent1.root MixedHistograms/GroupE_iCent1_hists.root DataOverlay/GroupE/GroupE_iCent1.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent1.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent1.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent1.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent2.root GroupE/GroupE_iCent2.root MixedHistograms/GroupE_iCent2_hists.root DataOverlay/GroupE/GroupE_iCent2.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent2.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent2.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent2.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent3.root GroupE/GroupE_iCent3.root MixedHistograms/GroupE_iCent3_hists.root DataOverlay/GroupE/GroupE_iCent3.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent3.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent3.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent3.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent4.root GroupE/GroupE_iCent4.root MixedHistograms/GroupE_iCent4_hists.root DataOverlay/GroupE/GroupE_iCent4.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent4.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent4.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent4.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent5.root GroupE/GroupE_iCent5.root MixedHistograms/GroupE_iCent5_hists.root DataOverlay/GroupE/GroupE_iCent5.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent5.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent5.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent5.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent6.root GroupE/GroupE_iCent6.root MixedHistograms/GroupE_iCent6_hists.root DataOverlay/GroupE/GroupE_iCent6.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent6.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent6.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent6.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent7.root GroupE/GroupE_iCent7.root MixedHistograms/GroupE_iCent7_hists.root DataOverlay/GroupE/GroupE_iCent7.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent7.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent7.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent7.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent8.root GroupE/GroupE_iCent8.root MixedHistograms/GroupE_iCent8_hists.root DataOverlay/GroupE/GroupE_iCent8.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent8.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent8.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent8.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent9.root GroupE/GroupE_iCent9.root MixedHistograms/GroupE_iCent9_hists.root DataOverlay/GroupE/GroupE_iCent9.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent9.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent9.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent9.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent10.root GroupE/GroupE_iCent10.root MixedHistograms/GroupE_iCent10_hists.root DataOverlay/GroupE/GroupE_iCent10.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent10.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent10.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent10.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent11.root GroupE/GroupE_iCent11.root MixedHistograms/GroupE_iCent11_hists.root DataOverlay/GroupE/GroupE_iCent11.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent11.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent11.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent11.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent12.root GroupE/GroupE_iCent12.root MixedHistograms/GroupE_iCent12_hists.root DataOverlay/GroupE/GroupE_iCent12.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent12.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent12.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent12.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent13.root GroupE/GroupE_iCent13.root MixedHistograms/GroupE_iCent13_hists.root DataOverlay/GroupE/GroupE_iCent13.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent13.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent13.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent13.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent14.root GroupE/GroupE_iCent14.root MixedHistograms/GroupE_iCent14_hists.root DataOverlay/GroupE/GroupE_iCent14.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent14.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent14.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent14.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent15.root GroupE/GroupE_iCent15.root MixedHistograms/GroupE_iCent15_hists.root DataOverlay/GroupE/GroupE_iCent15.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent15.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent15.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent15.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent16.root GroupE/GroupE_iCent16.root MixedHistograms/GroupE_iCent16_hists.root DataOverlay/GroupE/GroupE_iCent16.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent16.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent16.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent16.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent17.root GroupE/GroupE_iCent17.root MixedHistograms/GroupE_iCent17_hists.root DataOverlay/GroupE/GroupE_iCent17.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent17.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent17.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent17.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent18.root GroupE/GroupE_iCent18.root MixedHistograms/GroupE_iCent18_hists.root DataOverlay/GroupE/GroupE_iCent18.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent18.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent18.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent18.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent19.root GroupE/GroupE_iCent19.root MixedHistograms/GroupE_iCent19_hists.root DataOverlay/GroupE/GroupE_iCent19.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent19.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent19.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent19.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent20.root GroupE/GroupE_iCent20.root MixedHistograms/GroupE_iCent20_hists.root DataOverlay/GroupE/GroupE_iCent20.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent20.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent20.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent20.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent21.root GroupE/GroupE_iCent21.root MixedHistograms/GroupE_iCent21_hists.root DataOverlay/GroupE/GroupE_iCent21.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent21.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent21.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent21.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent22.root GroupE/GroupE_iCent22.root MixedHistograms/GroupE_iCent22_hists.root DataOverlay/GroupE/GroupE_iCent22.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent22.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent22.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent22.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent23.root GroupE/GroupE_iCent23.root MixedHistograms/GroupE_iCent23_hists.root DataOverlay/GroupE/GroupE_iCent23.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent23.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent23.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent23.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent24.root GroupE/GroupE_iCent24.root MixedHistograms/GroupE_iCent24_hists.root DataOverlay/GroupE/GroupE_iCent24.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent24.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent25.root GroupE/GroupE_iCent25.root MixedHistograms/GroupE_iCent25_hists.root DataOverlay/GroupE/GroupE_iCent25.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent25.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent26.root GroupE/GroupE_iCent26.root MixedHistograms/GroupE_iCent26_hists.root DataOverlay/GroupE/GroupE_iCent26.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent26.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent26.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent26.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent27.root GroupE/GroupE_iCent27.root MixedHistograms/GroupE_iCent27_hists.root DataOverlay/GroupE/GroupE_iCent27.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent27.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent27.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent27.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupE_iCent28.root GroupE/GroupE_iCent28.root MixedHistograms/GroupE_iCent28_hists.root DataOverlay/GroupE/GroupE_iCent28.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupE_iCent28.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupE_iCent28.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupE_iCent28.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent1.root GroupF/GroupF_iCent1.root MixedHistograms/GroupF_iCent1_hists.root DataOverlay/GroupF/GroupF_iCent1.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent1.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent1.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent1.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent2.root GroupF/GroupF_iCent2.root MixedHistograms/GroupF_iCent2_hists.root DataOverlay/GroupF/GroupF_iCent2.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent2.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent2.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent2.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent3.root GroupF/GroupF_iCent3.root MixedHistograms/GroupF_iCent3_hists.root DataOverlay/GroupF/GroupF_iCent3.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent3.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent3.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent3.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent4.root GroupF/GroupF_iCent4.root MixedHistograms/GroupF_iCent4_hists.root DataOverlay/GroupF/GroupF_iCent4.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent4.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent4.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent4.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent5.root GroupF/GroupF_iCent5.root MixedHistograms/GroupF_iCent5_hists.root DataOverlay/GroupF/GroupF_iCent5.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent5.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent5.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent5.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent6.root GroupF/GroupF_iCent6.root MixedHistograms/GroupF_iCent6_hists.root DataOverlay/GroupF/GroupF_iCent6.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent6.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent6.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent6.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent7.root GroupF/GroupF_iCent7.root MixedHistograms/GroupF_iCent7_hists.root DataOverlay/GroupF/GroupF_iCent7.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent7.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent7.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent7.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent8.root GroupF/GroupF_iCent8.root MixedHistograms/GroupF_iCent8_hists.root DataOverlay/GroupF/GroupF_iCent8.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent8.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent8.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent8.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent9.root GroupF/GroupF_iCent9.root MixedHistograms/GroupF_iCent9_hists.root DataOverlay/GroupF/GroupF_iCent9.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent9.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent9.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent9.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent10.root GroupF/GroupF_iCent10.root MixedHistograms/GroupF_iCent10_hists.root DataOverlay/GroupF/GroupF_iCent10.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent10.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent10.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent10.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent11.root GroupF/GroupF_iCent11.root MixedHistograms/GroupF_iCent11_hists.root DataOverlay/GroupF/GroupF_iCent11.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent11.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent11.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent11.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent12.root GroupF/GroupF_iCent12.root MixedHistograms/GroupF_iCent12_hists.root DataOverlay/GroupF/GroupF_iCent12.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent12.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent12.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent12.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent13.root GroupF/GroupF_iCent13.root MixedHistograms/GroupF_iCent13_hists.root DataOverlay/GroupF/GroupF_iCent13.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent13.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent13.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent13.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent14.root GroupF/GroupF_iCent14.root MixedHistograms/GroupF_iCent14_hists.root DataOverlay/GroupF/GroupF_iCent14.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent14.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent14.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent14.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent15.root GroupF/GroupF_iCent15.root MixedHistograms/GroupF_iCent15_hists.root DataOverlay/GroupF/GroupF_iCent15.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent15.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent15.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent15.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent16.root GroupF/GroupF_iCent16.root MixedHistograms/GroupF_iCent16_hists.root DataOverlay/GroupF/GroupF_iCent16.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent16.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent16.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent16.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent17.root GroupF/GroupF_iCent17.root MixedHistograms/GroupF_iCent17_hists.root DataOverlay/GroupF/GroupF_iCent17.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent17.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent17.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent17.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent18.root GroupF/GroupF_iCent18.root MixedHistograms/GroupF_iCent18_hists.root DataOverlay/GroupF/GroupF_iCent18.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent18.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent18.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent18.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent19.root GroupF/GroupF_iCent19.root MixedHistograms/GroupF_iCent19_hists.root DataOverlay/GroupF/GroupF_iCent19.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent19.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent19.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent19.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent20.root GroupF/GroupF_iCent20.root MixedHistograms/GroupF_iCent20_hists.root DataOverlay/GroupF/GroupF_iCent20.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent20.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent20.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent20.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent21.root GroupF/GroupF_iCent21.root MixedHistograms/GroupF_iCent21_hists.root DataOverlay/GroupF/GroupF_iCent21.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent21.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent21.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent21.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent22.root GroupF/GroupF_iCent22.root MixedHistograms/GroupF_iCent22_hists.root DataOverlay/GroupF/GroupF_iCent22.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent22.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent22.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent22.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent23.root GroupF/GroupF_iCent23.root MixedHistograms/GroupF_iCent23_hists.root DataOverlay/GroupF/GroupF_iCent23.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent23.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent23.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent23.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent24.root GroupF/GroupF_iCent24.root MixedHistograms/GroupF_iCent24_hists.root DataOverlay/GroupF/GroupF_iCent24.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent24.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent25.root GroupF/GroupF_iCent25.root MixedHistograms/GroupF_iCent25_hists.root DataOverlay/GroupF/GroupF_iCent25.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent25.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent26.root GroupF/GroupF_iCent26.root MixedHistograms/GroupF_iCent26_hists.root DataOverlay/GroupF/GroupF_iCent26.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent26.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent26.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent26.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent27.root GroupF/GroupF_iCent27.root MixedHistograms/GroupF_iCent27_hists.root DataOverlay/GroupF/GroupF_iCent27.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent27.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent27.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent27.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupF_iCent28.root GroupF/GroupF_iCent28.root MixedHistograms/GroupF_iCent28_hists.root DataOverlay/GroupF/GroupF_iCent28.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupF_iCent28.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupF_iCent28.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupF_iCent28.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent1.root GroupG/GroupG_iCent1.root MixedHistograms/GroupG_iCent1_hists.root DataOverlay/GroupG/GroupG_iCent1.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent1.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent1.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent1.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent2.root GroupG/GroupG_iCent2.root MixedHistograms/GroupG_iCent2_hists.root DataOverlay/GroupG/GroupG_iCent2.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent2.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent2.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent2.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent3.root GroupG/GroupG_iCent3.root MixedHistograms/GroupG_iCent3_hists.root DataOverlay/GroupG/GroupG_iCent3.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent3.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent3.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent3.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent4.root GroupG/GroupG_iCent4.root MixedHistograms/GroupG_iCent4_hists.root DataOverlay/GroupG/GroupG_iCent4.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent4.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent4.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent4.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent5.root GroupG/GroupG_iCent5.root MixedHistograms/GroupG_iCent5_hists.root DataOverlay/GroupG/GroupG_iCent5.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent5.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent5.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent5.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent6.root GroupG/GroupG_iCent6.root MixedHistograms/GroupG_iCent6_hists.root DataOverlay/GroupG/GroupG_iCent6.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent6.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent6.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent6.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent7.root GroupG/GroupG_iCent7.root MixedHistograms/GroupG_iCent7_hists.root DataOverlay/GroupG/GroupG_iCent7.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent7.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent7.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent7.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent8.root GroupG/GroupG_iCent8.root MixedHistograms/GroupG_iCent8_hists.root DataOverlay/GroupG/GroupG_iCent8.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent8.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent8.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent8.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent9.root GroupG/GroupG_iCent9.root MixedHistograms/GroupG_iCent9_hists.root DataOverlay/GroupG/GroupG_iCent9.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent9.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent9.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent9.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent10.root GroupG/GroupG_iCent10.root MixedHistograms/GroupG_iCent10_hists.root DataOverlay/GroupG/GroupG_iCent10.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent10.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent10.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent10.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent11.root GroupG/GroupG_iCent11.root MixedHistograms/GroupG_iCent11_hists.root DataOverlay/GroupG/GroupG_iCent11.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent11.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent11.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent11.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent12.root GroupG/GroupG_iCent12.root MixedHistograms/GroupG_iCent12_hists.root DataOverlay/GroupG/GroupG_iCent12.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent12.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent12.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent12.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent13.root GroupG/GroupG_iCent13.root MixedHistograms/GroupG_iCent13_hists.root DataOverlay/GroupG/GroupG_iCent13.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent13.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent13.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent13.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent14.root GroupG/GroupG_iCent14.root MixedHistograms/GroupG_iCent14_hists.root DataOverlay/GroupG/GroupG_iCent14.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent14.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent14.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent14.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent15.root GroupG/GroupG_iCent15.root MixedHistograms/GroupG_iCent15_hists.root DataOverlay/GroupG/GroupG_iCent15.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent15.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent15.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent15.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent16.root GroupG/GroupG_iCent16.root MixedHistograms/GroupG_iCent16_hists.root DataOverlay/GroupG/GroupG_iCent16.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent16.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent16.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent16.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent17.root GroupG/GroupG_iCent17.root MixedHistograms/GroupG_iCent17_hists.root DataOverlay/GroupG/GroupG_iCent17.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent17.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent17.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent17.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent18.root GroupG/GroupG_iCent18.root MixedHistograms/GroupG_iCent18_hists.root DataOverlay/GroupG/GroupG_iCent18.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent18.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent18.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent18.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent19.root GroupG/GroupG_iCent19.root MixedHistograms/GroupG_iCent19_hists.root DataOverlay/GroupG/GroupG_iCent19.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent19.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent19.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent19.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent20.root GroupG/GroupG_iCent20.root MixedHistograms/GroupG_iCent20_hists.root DataOverlay/GroupG/GroupG_iCent20.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent20.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent20.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent20.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent21.root GroupG/GroupG_iCent21.root MixedHistograms/GroupG_iCent21_hists.root DataOverlay/GroupG/GroupG_iCent21.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent21.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent21.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent21.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent22.root GroupG/GroupG_iCent22.root MixedHistograms/GroupG_iCent22_hists.root DataOverlay/GroupG/GroupG_iCent22.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent22.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent22.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent22.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent23.root GroupG/GroupG_iCent23.root MixedHistograms/GroupG_iCent23_hists.root DataOverlay/GroupG/GroupG_iCent23.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent23.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent23.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent23.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent24.root GroupG/GroupG_iCent24.root MixedHistograms/GroupG_iCent24_hists.root DataOverlay/GroupG/GroupG_iCent24.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent24.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent25.root GroupG/GroupG_iCent25.root MixedHistograms/GroupG_iCent25_hists.root DataOverlay/GroupG/GroupG_iCent25.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent25.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent26.root GroupG/GroupG_iCent26.root MixedHistograms/GroupG_iCent26_hists.root DataOverlay/GroupG/GroupG_iCent26.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent26.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent26.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent26.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent27.root GroupG/GroupG_iCent27.root MixedHistograms/GroupG_iCent27_hists.root DataOverlay/GroupG/GroupG_iCent27.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent27.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent27.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent27.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupG_iCent28.root GroupG/GroupG_iCent28.root MixedHistograms/GroupG_iCent28_hists.root DataOverlay/GroupG/GroupG_iCent28.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupG_iCent28.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupG_iCent28.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupG_iCent28.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent1.root GroupH/GroupH_iCent1.root MixedHistograms/GroupH_iCent1_hists.root DataOverlay/GroupH/GroupH_iCent1.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent1.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent1.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent1.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent2.root GroupH/GroupH_iCent2.root MixedHistograms/GroupH_iCent2_hists.root DataOverlay/GroupH/GroupH_iCent2.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent2.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent2.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent2.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent3.root GroupH/GroupH_iCent3.root MixedHistograms/GroupH_iCent3_hists.root DataOverlay/GroupH/GroupH_iCent3.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent3.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent3.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent3.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent4.root GroupH/GroupH_iCent4.root MixedHistograms/GroupH_iCent4_hists.root DataOverlay/GroupH/GroupH_iCent4.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent4.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent4.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent4.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent5.root GroupH/GroupH_iCent5.root MixedHistograms/GroupH_iCent5_hists.root DataOverlay/GroupH/GroupH_iCent5.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent5.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent5.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent5.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent6.root GroupH/GroupH_iCent6.root MixedHistograms/GroupH_iCent6_hists.root DataOverlay/GroupH/GroupH_iCent6.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent6.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent6.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent6.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent7.root GroupH/GroupH_iCent7.root MixedHistograms/GroupH_iCent7_hists.root DataOverlay/GroupH/GroupH_iCent7.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent7.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent7.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent7.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent8.root GroupH/GroupH_iCent8.root MixedHistograms/GroupH_iCent8_hists.root DataOverlay/GroupH/GroupH_iCent8.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent8.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent8.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent8.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent9.root GroupH/GroupH_iCent9.root MixedHistograms/GroupH_iCent9_hists.root DataOverlay/GroupH/GroupH_iCent9.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent9.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent9.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent9.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent10.root GroupH/GroupH_iCent10.root MixedHistograms/GroupH_iCent10_hists.root DataOverlay/GroupH/GroupH_iCent10.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent10.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent10.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent10.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent11.root GroupH/GroupH_iCent11.root MixedHistograms/GroupH_iCent11_hists.root DataOverlay/GroupH/GroupH_iCent11.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent11.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent11.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent11.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent12.root GroupH/GroupH_iCent12.root MixedHistograms/GroupH_iCent12_hists.root DataOverlay/GroupH/GroupH_iCent12.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent12.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent12.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent12.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent13.root GroupH/GroupH_iCent13.root MixedHistograms/GroupH_iCent13_hists.root DataOverlay/GroupH/GroupH_iCent13.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent13.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent13.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent13.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent14.root GroupH/GroupH_iCent14.root MixedHistograms/GroupH_iCent14_hists.root DataOverlay/GroupH/GroupH_iCent14.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent14.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent14.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent14.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent15.root GroupH/GroupH_iCent15.root MixedHistograms/GroupH_iCent15_hists.root DataOverlay/GroupH/GroupH_iCent15.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent15.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent15.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent15.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent16.root GroupH/GroupH_iCent16.root MixedHistograms/GroupH_iCent16_hists.root DataOverlay/GroupH/GroupH_iCent16.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent16.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent16.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent16.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent17.root GroupH/GroupH_iCent17.root MixedHistograms/GroupH_iCent17_hists.root DataOverlay/GroupH/GroupH_iCent17.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent17.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent17.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent17.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent18.root GroupH/GroupH_iCent18.root MixedHistograms/GroupH_iCent18_hists.root DataOverlay/GroupH/GroupH_iCent18.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent18.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent18.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent18.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent19.root GroupH/GroupH_iCent19.root MixedHistograms/GroupH_iCent19_hists.root DataOverlay/GroupH/GroupH_iCent19.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent19.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent19.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent19.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent20.root GroupH/GroupH_iCent20.root MixedHistograms/GroupH_iCent20_hists.root DataOverlay/GroupH/GroupH_iCent20.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent20.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent20.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent20.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent21.root GroupH/GroupH_iCent21.root MixedHistograms/GroupH_iCent21_hists.root DataOverlay/GroupH/GroupH_iCent21.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent21.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent21.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent21.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent22.root GroupH/GroupH_iCent22.root MixedHistograms/GroupH_iCent22_hists.root DataOverlay/GroupH/GroupH_iCent22.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent22.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent22.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent22.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent23.root GroupH/GroupH_iCent23.root MixedHistograms/GroupH_iCent23_hists.root DataOverlay/GroupH/GroupH_iCent23.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent23.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent23.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent23.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent24.root GroupH/GroupH_iCent24.root MixedHistograms/GroupH_iCent24_hists.root DataOverlay/GroupH/GroupH_iCent24.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent24.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent25.root GroupH/GroupH_iCent25.root MixedHistograms/GroupH_iCent25_hists.root DataOverlay/GroupH/GroupH_iCent25.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent25.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent26.root GroupH/GroupH_iCent26.root MixedHistograms/GroupH_iCent26_hists.root DataOverlay/GroupH/GroupH_iCent26.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent26.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent26.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent26.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent27.root GroupH/GroupH_iCent27.root MixedHistograms/GroupH_iCent27_hists.root DataOverlay/GroupH/GroupH_iCent27.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent27.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent27.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent27.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupH_iCent28.root GroupH/GroupH_iCent28.root MixedHistograms/GroupH_iCent28_hists.root DataOverlay/GroupH/GroupH_iCent28.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupH_iCent28.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupH_iCent28.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupH_iCent28.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent1.root GroupI/GroupI_iCent1.root MixedHistograms/GroupI_iCent1_hists.root DataOverlay/GroupI/GroupI_iCent1.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent1.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent1.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent1.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent2.root GroupI/GroupI_iCent2.root MixedHistograms/GroupI_iCent2_hists.root DataOverlay/GroupI/GroupI_iCent2.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent2.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent2.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent2.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent3.root GroupI/GroupI_iCent3.root MixedHistograms/GroupI_iCent3_hists.root DataOverlay/GroupI/GroupI_iCent3.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent3.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent3.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent3.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent4.root GroupI/GroupI_iCent4.root MixedHistograms/GroupI_iCent4_hists.root DataOverlay/GroupI/GroupI_iCent4.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent4.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent4.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent4.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent5.root GroupI/GroupI_iCent5.root MixedHistograms/GroupI_iCent5_hists.root DataOverlay/GroupI/GroupI_iCent5.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent5.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent5.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent5.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent6.root GroupI/GroupI_iCent6.root MixedHistograms/GroupI_iCent6_hists.root DataOverlay/GroupI/GroupI_iCent6.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent6.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent6.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent6.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent7.root GroupI/GroupI_iCent7.root MixedHistograms/GroupI_iCent7_hists.root DataOverlay/GroupI/GroupI_iCent7.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent7.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent7.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent7.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent8.root GroupI/GroupI_iCent8.root MixedHistograms/GroupI_iCent8_hists.root DataOverlay/GroupI/GroupI_iCent8.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent8.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent8.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent8.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent9.root GroupI/GroupI_iCent9.root MixedHistograms/GroupI_iCent9_hists.root DataOverlay/GroupI/GroupI_iCent9.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent9.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent9.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent9.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent10.root GroupI/GroupI_iCent10.root MixedHistograms/GroupI_iCent10_hists.root DataOverlay/GroupI/GroupI_iCent10.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent10.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent10.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent10.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent11.root GroupI/GroupI_iCent11.root MixedHistograms/GroupI_iCent11_hists.root DataOverlay/GroupI/GroupI_iCent11.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent11.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent11.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent11.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent12.root GroupI/GroupI_iCent12.root MixedHistograms/GroupI_iCent12_hists.root DataOverlay/GroupI/GroupI_iCent12.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent12.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent12.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent12.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent13.root GroupI/GroupI_iCent13.root MixedHistograms/GroupI_iCent13_hists.root DataOverlay/GroupI/GroupI_iCent13.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent13.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent13.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent13.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent14.root GroupI/GroupI_iCent14.root MixedHistograms/GroupI_iCent14_hists.root DataOverlay/GroupI/GroupI_iCent14.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent14.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent14.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent14.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent15.root GroupI/GroupI_iCent15.root MixedHistograms/GroupI_iCent15_hists.root DataOverlay/GroupI/GroupI_iCent15.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent15.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent15.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent15.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent16.root GroupI/GroupI_iCent16.root MixedHistograms/GroupI_iCent16_hists.root DataOverlay/GroupI/GroupI_iCent16.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent16.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent16.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent16.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent17.root GroupI/GroupI_iCent17.root MixedHistograms/GroupI_iCent17_hists.root DataOverlay/GroupI/GroupI_iCent17.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent17.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent17.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent17.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent18.root GroupI/GroupI_iCent18.root MixedHistograms/GroupI_iCent18_hists.root DataOverlay/GroupI/GroupI_iCent18.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent18.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent18.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent18.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent19.root GroupI/GroupI_iCent19.root MixedHistograms/GroupI_iCent19_hists.root DataOverlay/GroupI/GroupI_iCent19.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent19.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent19.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent19.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent20.root GroupI/GroupI_iCent20.root MixedHistograms/GroupI_iCent20_hists.root DataOverlay/GroupI/GroupI_iCent20.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent20.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent20.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent20.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent21.root GroupI/GroupI_iCent21.root MixedHistograms/GroupI_iCent21_hists.root DataOverlay/GroupI/GroupI_iCent21.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent21.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent21.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent21.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent22.root GroupI/GroupI_iCent22.root MixedHistograms/GroupI_iCent22_hists.root DataOverlay/GroupI/GroupI_iCent22.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent22.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent22.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent22.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent23.root GroupI/GroupI_iCent23.root MixedHistograms/GroupI_iCent23_hists.root DataOverlay/GroupI/GroupI_iCent23.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent23.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent23.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent23.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent24.root GroupI/GroupI_iCent24.root MixedHistograms/GroupI_iCent24_hists.root DataOverlay/GroupI/GroupI_iCent24.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent24.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent25.root GroupI/GroupI_iCent25.root MixedHistograms/GroupI_iCent25_hists.root DataOverlay/GroupI/GroupI_iCent25.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent25.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent26.root GroupI/GroupI_iCent26.root MixedHistograms/GroupI_iCent26_hists.root DataOverlay/GroupI/GroupI_iCent26.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent26.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent26.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent26.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent27.root GroupI/GroupI_iCent27.root MixedHistograms/GroupI_iCent27_hists.root DataOverlay/GroupI/GroupI_iCent27.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent27.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent27.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent27.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupI_iCent28.root GroupI/GroupI_iCent28.root MixedHistograms/GroupI_iCent28_hists.root DataOverlay/GroupI/GroupI_iCent28.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupI_iCent28.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupI_iCent28.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupI_iCent28.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent1.root GroupJ/GroupJ_iCent1.root MixedHistograms/GroupJ_iCent1_hists.root DataOverlay/GroupJ/GroupJ_iCent1.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent1.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent1.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent1.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent2.root GroupJ/GroupJ_iCent2.root MixedHistograms/GroupJ_iCent2_hists.root DataOverlay/GroupJ/GroupJ_iCent2.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent2.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent2.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent2.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent3.root GroupJ/GroupJ_iCent3.root MixedHistograms/GroupJ_iCent3_hists.root DataOverlay/GroupJ/GroupJ_iCent3.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent3.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent3.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent3.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent4.root GroupJ/GroupJ_iCent4.root MixedHistograms/GroupJ_iCent4_hists.root DataOverlay/GroupJ/GroupJ_iCent4.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent4.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent4.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent4.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent5.root GroupJ/GroupJ_iCent5.root MixedHistograms/GroupJ_iCent5_hists.root DataOverlay/GroupJ/GroupJ_iCent5.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent5.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent5.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent5.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent6.root GroupJ/GroupJ_iCent6.root MixedHistograms/GroupJ_iCent6_hists.root DataOverlay/GroupJ/GroupJ_iCent6.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent6.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent6.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent6.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent7.root GroupJ/GroupJ_iCent7.root MixedHistograms/GroupJ_iCent7_hists.root DataOverlay/GroupJ/GroupJ_iCent7.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent7.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent7.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent7.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent8.root GroupJ/GroupJ_iCent8.root MixedHistograms/GroupJ_iCent8_hists.root DataOverlay/GroupJ/GroupJ_iCent8.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent8.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent8.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent8.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent9.root GroupJ/GroupJ_iCent9.root MixedHistograms/GroupJ_iCent9_hists.root DataOverlay/GroupJ/GroupJ_iCent9.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent9.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent9.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent9.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent10.root GroupJ/GroupJ_iCent10.root MixedHistograms/GroupJ_iCent10_hists.root DataOverlay/GroupJ/GroupJ_iCent10.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent10.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent10.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent10.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent11.root GroupJ/GroupJ_iCent11.root MixedHistograms/GroupJ_iCent11_hists.root DataOverlay/GroupJ/GroupJ_iCent11.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent11.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent11.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent11.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent12.root GroupJ/GroupJ_iCent12.root MixedHistograms/GroupJ_iCent12_hists.root DataOverlay/GroupJ/GroupJ_iCent12.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent12.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent12.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent12.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent13.root GroupJ/GroupJ_iCent13.root MixedHistograms/GroupJ_iCent13_hists.root DataOverlay/GroupJ/GroupJ_iCent13.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent13.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent13.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent13.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent14.root GroupJ/GroupJ_iCent14.root MixedHistograms/GroupJ_iCent14_hists.root DataOverlay/GroupJ/GroupJ_iCent14.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent14.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent14.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent14.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent15.root GroupJ/GroupJ_iCent15.root MixedHistograms/GroupJ_iCent15_hists.root DataOverlay/GroupJ/GroupJ_iCent15.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent15.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent15.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent15.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent16.root GroupJ/GroupJ_iCent16.root MixedHistograms/GroupJ_iCent16_hists.root DataOverlay/GroupJ/GroupJ_iCent16.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent16.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent16.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent16.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent17.root GroupJ/GroupJ_iCent17.root MixedHistograms/GroupJ_iCent17_hists.root DataOverlay/GroupJ/GroupJ_iCent17.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent17.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent17.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent17.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent18.root GroupJ/GroupJ_iCent18.root MixedHistograms/GroupJ_iCent18_hists.root DataOverlay/GroupJ/GroupJ_iCent18.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent18.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent18.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent18.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent19.root GroupJ/GroupJ_iCent19.root MixedHistograms/GroupJ_iCent19_hists.root DataOverlay/GroupJ/GroupJ_iCent19.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent19.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent19.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent19.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent20.root GroupJ/GroupJ_iCent20.root MixedHistograms/GroupJ_iCent20_hists.root DataOverlay/GroupJ/GroupJ_iCent20.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent20.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent20.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent20.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent21.root GroupJ/GroupJ_iCent21.root MixedHistograms/GroupJ_iCent21_hists.root DataOverlay/GroupJ/GroupJ_iCent21.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent21.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent21.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent21.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent22.root GroupJ/GroupJ_iCent22.root MixedHistograms/GroupJ_iCent22_hists.root DataOverlay/GroupJ/GroupJ_iCent22.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent22.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent22.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent22.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent23.root GroupJ/GroupJ_iCent23.root MixedHistograms/GroupJ_iCent23_hists.root DataOverlay/GroupJ/GroupJ_iCent23.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent23.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent23.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent23.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent24.root GroupJ/GroupJ_iCent24.root MixedHistograms/GroupJ_iCent24_hists.root DataOverlay/GroupJ/GroupJ_iCent24.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent24.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent25.root GroupJ/GroupJ_iCent25.root MixedHistograms/GroupJ_iCent25_hists.root DataOverlay/GroupJ/GroupJ_iCent25.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent25.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent26.root GroupJ/GroupJ_iCent26.root MixedHistograms/GroupJ_iCent26_hists.root DataOverlay/GroupJ/GroupJ_iCent26.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent26.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent26.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent26.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent27.root GroupJ/GroupJ_iCent27.root MixedHistograms/GroupJ_iCent27_hists.root DataOverlay/GroupJ/GroupJ_iCent27.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent27.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent27.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent27.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupJ_iCent28.root GroupJ/GroupJ_iCent28.root MixedHistograms/GroupJ_iCent28_hists.root DataOverlay/GroupJ/GroupJ_iCent28.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupJ_iCent28.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupJ_iCent28.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupJ_iCent28.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent1.root GroupK/GroupK_iCent1.root MixedHistograms/GroupK_iCent1_hists.root DataOverlay/GroupK/GroupK_iCent1.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent1.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent1.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent1.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent2.root GroupK/GroupK_iCent2.root MixedHistograms/GroupK_iCent2_hists.root DataOverlay/GroupK/GroupK_iCent2.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent2.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent2.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent2.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent3.root GroupK/GroupK_iCent3.root MixedHistograms/GroupK_iCent3_hists.root DataOverlay/GroupK/GroupK_iCent3.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent3.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent3.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent3.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent4.root GroupK/GroupK_iCent4.root MixedHistograms/GroupK_iCent4_hists.root DataOverlay/GroupK/GroupK_iCent4.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent4.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent4.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent4.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent5.root GroupK/GroupK_iCent5.root MixedHistograms/GroupK_iCent5_hists.root DataOverlay/GroupK/GroupK_iCent5.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent5.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent5.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent5.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent6.root GroupK/GroupK_iCent6.root MixedHistograms/GroupK_iCent6_hists.root DataOverlay/GroupK/GroupK_iCent6.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent6.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent6.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent6.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent7.root GroupK/GroupK_iCent7.root MixedHistograms/GroupK_iCent7_hists.root DataOverlay/GroupK/GroupK_iCent7.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent7.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent7.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent7.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent8.root GroupK/GroupK_iCent8.root MixedHistograms/GroupK_iCent8_hists.root DataOverlay/GroupK/GroupK_iCent8.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent8.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent8.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent8.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent9.root GroupK/GroupK_iCent9.root MixedHistograms/GroupK_iCent9_hists.root DataOverlay/GroupK/GroupK_iCent9.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent9.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent9.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent9.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent10.root GroupK/GroupK_iCent10.root MixedHistograms/GroupK_iCent10_hists.root DataOverlay/GroupK/GroupK_iCent10.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent10.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent10.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent10.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent11.root GroupK/GroupK_iCent11.root MixedHistograms/GroupK_iCent11_hists.root DataOverlay/GroupK/GroupK_iCent11.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent11.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent11.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent11.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent12.root GroupK/GroupK_iCent12.root MixedHistograms/GroupK_iCent12_hists.root DataOverlay/GroupK/GroupK_iCent12.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent12.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent12.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent12.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent13.root GroupK/GroupK_iCent13.root MixedHistograms/GroupK_iCent13_hists.root DataOverlay/GroupK/GroupK_iCent13.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent13.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent13.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent13.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent14.root GroupK/GroupK_iCent14.root MixedHistograms/GroupK_iCent14_hists.root DataOverlay/GroupK/GroupK_iCent14.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent14.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent14.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent14.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent15.root GroupK/GroupK_iCent15.root MixedHistograms/GroupK_iCent15_hists.root DataOverlay/GroupK/GroupK_iCent15.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent15.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent15.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent15.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent16.root GroupK/GroupK_iCent16.root MixedHistograms/GroupK_iCent16_hists.root DataOverlay/GroupK/GroupK_iCent16.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent16.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent16.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent16.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent17.root GroupK/GroupK_iCent17.root MixedHistograms/GroupK_iCent17_hists.root DataOverlay/GroupK/GroupK_iCent17.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent17.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent17.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent17.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent18.root GroupK/GroupK_iCent18.root MixedHistograms/GroupK_iCent18_hists.root DataOverlay/GroupK/GroupK_iCent18.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent18.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent18.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent18.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent19.root GroupK/GroupK_iCent19.root MixedHistograms/GroupK_iCent19_hists.root DataOverlay/GroupK/GroupK_iCent19.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent19.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent19.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent19.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent20.root GroupK/GroupK_iCent20.root MixedHistograms/GroupK_iCent20_hists.root DataOverlay/GroupK/GroupK_iCent20.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent20.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent20.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent20.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent21.root GroupK/GroupK_iCent21.root MixedHistograms/GroupK_iCent21_hists.root DataOverlay/GroupK/GroupK_iCent21.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent21.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent21.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent21.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent22.root GroupK/GroupK_iCent22.root MixedHistograms/GroupK_iCent22_hists.root DataOverlay/GroupK/GroupK_iCent22.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent22.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent22.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent22.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent23.root GroupK/GroupK_iCent23.root MixedHistograms/GroupK_iCent23_hists.root DataOverlay/GroupK/GroupK_iCent23.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent23.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent23.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent23.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent24.root GroupK/GroupK_iCent24.root MixedHistograms/GroupK_iCent24_hists.root DataOverlay/GroupK/GroupK_iCent24.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent24.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent25.root GroupK/GroupK_iCent25.root MixedHistograms/GroupK_iCent25_hists.root DataOverlay/GroupK/GroupK_iCent25.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent25.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent26.root GroupK/GroupK_iCent26.root MixedHistograms/GroupK_iCent26_hists.root DataOverlay/GroupK/GroupK_iCent26.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent26.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent26.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent26.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent27.root GroupK/GroupK_iCent27.root MixedHistograms/GroupK_iCent27_hists.root DataOverlay/GroupK/GroupK_iCent27.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent27.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent27.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent27.out
Queue 1

Arguments = mcminbias CombinedTrees/GroupK_iCent28.root GroupK/GroupK_iCent28.root MixedHistograms/GroupK_iCent28_hists.root DataOverlay/GroupK/GroupK_iCent28.root true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/GroupK_iCent28.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/GroupK_iCent28.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/GroupK_iCent28.out
Queue 1

