Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Macros/ProcessFile.exe
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Macros
accounting_group = group_atlas.boulder
request_memory   = 2G

sysFlags = false none

Arguments = minbias 340644.root 0 340644_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340644_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340644_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340644_minbias.out
Queue 1

Arguments = minbias 340683.root 0 340683_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340683_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340683_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340683_minbias.out
Queue 1

Arguments = minbias 340697.root 0 340697_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340697_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340697_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340697_minbias.out
Queue 1

Arguments = minbias 340718.root 0 340718_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340718_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340718_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340718_minbias.out
Queue 1

Arguments = minbias 340814.root 0 340814_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340814_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340814_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340814_minbias.out
Queue 1

Arguments = minbias 340849.root 0 340849_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340849_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340849_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340849_minbias.out
Queue 1

Arguments = minbias 340850.root 0 340850_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340850_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340850_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340850_minbias.out
Queue 1

Arguments = minbias 340910.root 0 340910_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340910_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340910_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340910_minbias.out
Queue 1

Arguments = minbias 340925.root 0 340925_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340925_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340925_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340925_minbias.out
Queue 1

Arguments = minbias 340973.root 0 340973_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/340973_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/340973_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/340973_minbias.out
Queue 1

Arguments = minbias 341027.root 0 341027_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/341027_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/341027_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/341027_minbias.out
Queue 1

Arguments = minbias 341123.root 0 341123_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/341123_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/341123_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/341123_minbias.out
Queue 1

Arguments = minbias 341184.root 0 341184_hists.root 0 false $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/errors/341184_minbias.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/logs/341184_minbias.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Submit/outputs/341184_minbias.out
Queue 1
