Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Macros/ProcessFile
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Macros
accounting_group = group_atlas.boulder
request_memory   = 8 GB

sysFlags = false none


#Arguments = minbias GroupA/GroupA_iCent$(iCent).root 0 GroupA/GroupA_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupA_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupA_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupA_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupB/GroupB_iCent$(iCent).root 0 GroupB/GroupB_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupB_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupB_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupB_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupC/GroupC_iCent$(iCent).root 0 GroupC/GroupC_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupC_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupC_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupC_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupD/GroupD_iCent$(iCent).root 0 GroupD/GroupD_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupD_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupD_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupD_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupE/GroupE_iCent$(iCent).root 0 GroupE/GroupE_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupE_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupE_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupE_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupF/GroupF_iCent$(iCent).root 0 GroupF/GroupF_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupF_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupF_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupF_iCent$(iCent).out
#Queue iCent in (3)
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupG/GroupG_iCent$(iCent).root 0 GroupG/GroupG_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupG_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupG_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupG_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
Arguments = minbias GroupH/GroupH_iCent$(iCent).root 0 GroupH/GroupH_iCent$(iCent)_hists.root 0 true $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupH_iCent$(iCent).err
Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupH_iCent$(iCent).log
Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupH_iCent$(iCent).out
Queue iCent in (3)
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupI/GroupI_iCent$(iCent).root 0 GroupI/GroupI_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupI_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupI_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupI_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupJ/GroupJ_iCent$(iCent).root 0 GroupJ/GroupJ_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupJ_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupJ_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupJ_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
#
#Arguments = minbias GroupK/GroupK_iCent$(iCent).root 0 GroupK/GroupK_iCent$(iCent)_hists.root 0 true $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/errors/GroupK_iCent$(iCent).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/logs/GroupK_iCent$(iCent).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/atlas-hi/ZTrackAnalysis/Submit/outputs/GroupK_iCent$(iCent).out
#Queue iCent in (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28)
