Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/bin/run.exe.exe
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run
accounting_group = group_atlas.boulder

sysFlags = false false false false false false false false


Arguments = false BkgEstimator data_100 365502 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365502.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365502.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365502.out
Queue 1

Arguments = false BkgEstimator data_100 365512 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365512.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365512.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365512.out
Queue 1

Arguments = false BkgEstimator data_100 365573 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365573.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365573.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365573.out
Queue 1

Arguments = false BkgEstimator data_100 365602 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365602.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365602.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365602.out
Queue 1

Arguments = false BkgEstimator data_100 365627 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365627.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365627.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365627.out
Queue 1

Arguments = false BkgEstimator data_100 365678 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365678.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365678.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365678.out
Queue 1

Arguments = false BkgEstimator data_100 365681 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365681.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365681.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365681.out
Queue 1

Arguments = false BkgEstimator data_100 365709 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365709.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365709.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365709.out
Queue 1

Arguments = false BkgEstimator data_100 365752 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365752.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365752.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365752.out
Queue 1

Arguments = false BkgEstimator data_100 365834 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365834.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365834.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365834.out
Queue 1

Arguments = false BkgEstimator data_100 365914 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365914.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365914.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365914.out
Queue 1

Arguments = false BkgEstimator data_100 365932 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/365932.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/365932.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/365932.out
Queue 1

Arguments = false BkgEstimator data_100 366011 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366011.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366011.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366011.out
Queue 1

Arguments = false BkgEstimator data_100 366029 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366029.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366029.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366029.out
Queue 1

Arguments = false BkgEstimator data_100 366092 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366092.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366092.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366092.out
Queue 1

Arguments = false BkgEstimator data_100 366142 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366142.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366142.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366142.out
Queue 1

Arguments = false BkgEstimator data_100 366268 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366268.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366268.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366268.out
Queue 1

Arguments = false BkgEstimator data_100 366337 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366337.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366337.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366337.out
Queue 1

Arguments = false BkgEstimator data_100 366383 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366383.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366383.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366383.out
Queue 1

Arguments = false BkgEstimator data_100 366413 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366413.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366413.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366413.out
Queue 1

Arguments = false BkgEstimator data_100 366476 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366476.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366476.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366476.out
Queue 1

Arguments = false BkgEstimator data_100 366526 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366526.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366526.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366526.out
Queue 1

Arguments = false BkgEstimator data_100 366528 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366528.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366528.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366528.out
Queue 1

Arguments = false BkgEstimator data_100 366627 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366627.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366627.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366627.out
Queue 1

Arguments = false BkgEstimator data_100 366691 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366691.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366691.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366691.out
Queue 1

Arguments = false BkgEstimator data_100 366754 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366754.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366754.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366754.out
Queue 1

Arguments = false BkgEstimator data_100 366805 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366805.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366805.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366805.out
Queue 1

Arguments = false BkgEstimator data_100 366860 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366860.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366860.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366860.out
Queue 1

Arguments = false BkgEstimator data_100 366878 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366878.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366878.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366878.out
Queue 1

Arguments = false BkgEstimator data_100 366919 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366919.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366919.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366919.out
Queue 1

Arguments = false BkgEstimator data_100 366931 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366931.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366931.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366931.out
Queue 1

Arguments = false BkgEstimator data_100 366994 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/366994.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/366994.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/366994.out
Queue 1

Arguments = false BkgEstimator data_100 367023 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367023.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367023.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367023.out
Queue 1

Arguments = false BkgEstimator data_100 367099 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367099.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367099.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367099.out
Queue 1

Arguments = false BkgEstimator data_100 367134 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367134.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367134.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367134.out
Queue 1

Arguments = false BkgEstimator data_100 367165 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367165.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367165.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367165.out
Queue 1

Arguments = false BkgEstimator data_100 367170 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367170.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367170.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367170.out
Queue 1

Arguments = false BkgEstimator data_100 367233 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367233.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367233.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367233.out
Queue 1

Arguments = false BkgEstimator data_100 367273 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367273.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367273.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367273.out
Queue 1

Arguments = false BkgEstimator data_100 367318 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367318.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367318.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367318.out
Queue 1

Arguments = false BkgEstimator data_100 367321 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367321.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367321.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367321.out
Queue 1

Arguments = false BkgEstimator data_100 367363 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367363.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367363.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367363.out
Queue 1

Arguments = false BkgEstimator data_100 367364 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367364.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367364.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367364.out
Queue 1

Arguments = false BkgEstimator data_100 367365 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367365.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367365.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367365.out
Queue 1

Arguments = false BkgEstimator data_100 367384 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/367384.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/367384.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/367384.out
Queue 1




Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 642.830 1 357861 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.361107.pp_Zmumu.recon.AOD.e4916_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pp_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pp_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pp_Zmumu.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.520 0.99997 541661 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420067.pn_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pn_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pn_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pn_Zmumu.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.450 0.99996 561006 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420068.np_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_np_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_np_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_np_Zmumu.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 665.320 0.99995 840470 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420069.nn_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_nn_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_nn_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_nn_Zmumu.out
Queue 1

Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 642.830 1 415887 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.361106.pp_Zee.recon.AOD.e4916_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pp_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pp_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pp_Zee.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.580 0.99997 638346 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420121.pn_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pn_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pn_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pn_Zee.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.430 0.99997 638321 user.jeouelle.21.2.82.ztrack.101.mc16_5TeV.PbPb.420122.np_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_np_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_np_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_np_Zee.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 665.300 0.99994 976912 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420123.nn_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_nn_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_nn_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_nn_Zee.out
Queue 1




Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 642.830 0.1793 357894 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420090.pp_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pp_Zmumu_ptmin25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pp_Zmumu_ptmin25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pp_Zmumu_ptmin25.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.510 0.17947 560953 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420070.pn_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pn_Zmumu_ptmin25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pn_Zmumu_ptmin25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pn_Zmumu_ptmin25.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.480 0.17991 560953 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420071.np_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_np_Zmumu_ptmin25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_np_Zmumu_ptmin25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_np_Zmumu_ptmin25.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 665.340 0.17981 841487 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420072.nn_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_nn_Zmumu_ptmin25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_nn_Zmumu_ptmin25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_nn_Zmumu_ptmin25.out
Queue 1

Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 642.830 0.1793 415862 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420127.pp_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pp_Zee_ptmin25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pp_Zee_ptmin25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pp_Zee_ptmin25.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.580 0.17947 638366 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420124.pn_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pn_Zee_ptmin25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pn_Zee_ptmin25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pn_Zee_ptmin25.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.430 0.17991 638366 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420125.np_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_np_Zee_ptmin25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_np_Zee_ptmin25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_np_Zee_ptmin25.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 665.300 0.17981 976816 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420126.nn_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_nn_Zee_ptmin25.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_nn_Zee_ptmin25.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_nn_Zee_ptmin25.out
Queue 1




Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 642.810 0.36736 357900 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420293.pp_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pp_Zmumu_ygt175.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pp_Zmumu_ygt175.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pp_Zmumu_ygt175.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.500 0.37292 560051 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420290.pn_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pn_Zmumu_ygt175.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pn_Zmumu_ygt175.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pn_Zmumu_ygt175.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.510 0.37264 561091 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420291.np_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_np_Zmumu_ygt175.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_np_Zmumu_ygt175.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_np_Zmumu_ygt175.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 665.370 0.37864 839951 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420292.nn_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_nn_Zmumu_ygt175.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_nn_Zmumu_ygt175.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_nn_Zmumu_ygt175.out
Queue 1

Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 642.830 0.36778 415862 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420297.pp_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pp_Zee_ygt175.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pp_Zee_ygt175.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pp_Zee_ygt175.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.520 0.37302 638366 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420294.pn_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_pn_Zee_ygt175.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_pn_Zee_ygt175.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_pn_Zee_ygt175.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 656.500 0.37264 637401 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420295.np_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_np_Zee_ygt175.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_np_Zee_ygt175.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_np_Zee_ygt175.out
Queue 1
Arguments = false BkgEstimator mc_100 0 true PbPb18 $(sysFlags) 665.350 0.37864 976816 user.jeouelle.21.2.82.ztrack.100.mc16_5TeV.PbPb.420296.nn_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_nn_Zee_ygt175.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_nn_Zee_ygt175.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_nn_Zee_ygt175.out
Queue 1
