Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/bin/run.exe
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run
accounting_group = group_atlas.boulder

sysFlags = false false false false false false false false


#Arguments = false TruthSelectedTreeMaker mc_200 0 true pp17 $(sysFlags) 642.820 1 1000000 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.pp.361106.Zee.recon.AOD.e4916_s3238_r10313_r10210_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/pp_Zee.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/pp_Zee.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/pp_Zee.out
#Queue 1
#Arguments = false TruthSelectedTreeMaker mc_200 0 true pp17 $(sysFlags) 642.850 1 3360000 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.pp.361107.Zmumu.recon.AOD.e4916_s3238_r10313_r10726_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/pp_Zmumu.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/pp_Zmumu.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/pp_Zmumu.out
#Queue 1




Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3541_r11892_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_n64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_n64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_n64.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3540_r11893_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_n24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_n24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_n24.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3537_r11894_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_0.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_0.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_0.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3538_r11895_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_p24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_p24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_p24.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3539_r11898_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_p64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_p64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_p64.out
Queue 1




Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3541_r11899_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_n64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_n64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_n64.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3540_r11900_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_n24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_n24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_n24.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3537_r11901_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_0.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_0.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_0.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3538_r11902_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_p24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_p24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_p24.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3539_r11903_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_p64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_p64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_p64.out
Queue 1




Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3541_r11892_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_MB_vtxz_n64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_MB_vtxz_n64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_n64.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3540_r11893_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_MB_vtxz_n24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_MB_vtxz_n24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_n24.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3537_r11894_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_MB_vtxz_0.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_MB_vtxz_0.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_0.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3538_r11895_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_MB_vtxz_p24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_MB_vtxz_p24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_p24.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3539_r11898_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_MB_vtxz_p64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_MB_vtxz_p64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_p64.out
Queue 1




Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3541_r11899_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_SC_vtxz_n64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_SC_vtxz_n64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_n64.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3540_r11900_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_SC_vtxz_n24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_SC_vtxz_n24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_n24.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3537_r11901_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_SC_vtxz_0.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_SC_vtxz_0.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_0.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3538_r11902_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_SC_vtxz_p24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_SC_vtxz_p24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_p24.out
Queue 1
Arguments = false TruthSelectedTreeMaker hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3539_r11903_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb18_Zee_Hijing_SC_vtxz_p64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb18_Zee_Hijing_SC_vtxz_p64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_p64.out
Queue 1




## Egamma supercluster reconstruction in PbPb validation sample
#Arguments = false TruthSelectedTreeMaker hijing_110 0 true PbPb18 $(sysFlags) 642.820 1 100000 user.jeouelle.21.2.82.ztrack.110.mc16_valid.PbPb.Hijing.361106.Zee.recon.AOD.e4916_s2873_r11092_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/errors/PbPb_Zee_Hijing.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/logs/PbPb_Zee_Hijing.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/AnalysisCode/run/outputs/PbPb_Zee_Hijing.out
#Queue 1
