Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/bin/run
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run
accounting_group = group_atlas.boulder

dataFlag = cc_200
sysFlags = false false false false false false false false
#sysFlags = false false false false false false true false

#Arguments = false MinBiasTreeMaker $(dataFlag) 365502 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365502_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365502_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365502_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365512 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365512_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365512_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365512_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365573 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365573_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365573_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365573_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365602 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365602_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365602_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365602_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365627 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365627_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365627_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365627_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365678 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365678_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365678_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365678_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365681 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365681_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365681_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365681_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365709 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365709_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365709_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365709_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365752 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365752_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365752_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365752_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365834 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365834_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365834_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365834_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365914 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365914_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365914_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365914_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 365932 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365932_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365932_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365932_cc.out
#Queue 1

#Arguments = false MinBiasTreeMaker $(dataFlag) 366011 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366011_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366011_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366011_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366029 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366029_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366029_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366029_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366092 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366092_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366092_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366092_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366142 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366142_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366142_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366142_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366268 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366268_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366268_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366268_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366337 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366337_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366337_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366337_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366383 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366383_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366383_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366383_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366413 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366413_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366413_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366413_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366476 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366476_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366476_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366476_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366526 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366526_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366526_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366526_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366528 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366528_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366528_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366528_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366627 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366627_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366627_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366627_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366691 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366691_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366691_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366691_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366754 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366754_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366754_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366754_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366805 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366805_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366805_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366805_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366860 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366860_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366860_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366860_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366878 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366878_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366878_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366878_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366919 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366919_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366919_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366919_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366931 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366931_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366931_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366931_cc.out
#Queue 1
#
#Arguments = false MinBiasTreeMaker $(dataFlag) 366994 false PbPb18 $(sysFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366994_cc.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366994_cc.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366994_cc.out
#Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367023 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367023_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367023_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367023_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367099 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367099_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367099_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367099_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367134 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367134_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367134_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367134_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367165 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367165_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367165_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367165_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367170 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367170_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367170_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367170_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367233 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367233_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367233_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367233_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367273 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367273_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367273_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367273_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367318 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367318_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367318_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367318_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367321 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367321_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367321_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367321_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367363 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367363_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367363_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367363_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367364 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367364_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367364_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367364_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367365 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367365_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367365_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367365_cc.out
Queue 1

Arguments = false MinBiasTreeMaker $(dataFlag) 367384 false PbPb18 $(sysFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367384_cc.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367384_cc.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367384_cc.out
Queue 1
