Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/bin/run
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run
accounting_group = group_atlas.boulder

sysFlags = false false false false false false false false
#sysFlags = false false false false false false true false
#sysFlags = false false false false false false false true



Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3541_r11892_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_n64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_n64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_n64.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3540_r11893_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_n24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_n24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_n24.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3537_r11894_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_0.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_0.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_0.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3538_r11895_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_p24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_p24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_p24.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361107.Zmumu.recon.AOD.e4916_s3539_r11898_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_MB_vtxz_p64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_MB_vtxz_p64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_MB_vtxz_p64.out
Queue 1




Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3541_r11899_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_n64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_n64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_n64.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3540_r11900_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_n24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_n24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_n24.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3537_r11901_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_0.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_0.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_0.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3538_r11902_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_p24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_p24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_p24.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361107.Zmumu.recon.AOD.e4916_s3539_r11903_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zmumu_Hijing_SC_vtxz_p64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zmumu_Hijing_SC_vtxz_p64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zmumu_Hijing_SC_vtxz_p64.out
Queue 1




Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3541_r11892_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_MB_vtxz_n64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_MB_vtxz_n64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_n64.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3540_r11893_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_MB_vtxz_n24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_MB_vtxz_n24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_n24.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3537_r11894_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_MB_vtxz_0.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_MB_vtxz_0.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_0.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3538_r11895_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_MB_vtxz_p24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_MB_vtxz_p24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_p24.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 20000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Flow.361106.Zee.recon.AOD.e4916_s3539_r11898_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_MB_vtxz_p64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_MB_vtxz_p64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_MB_vtxz_p64.out
Queue 1




Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3541_r11899_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_SC_vtxz_n64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_SC_vtxz_n64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_n64.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3540_r11900_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_SC_vtxz_n24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_SC_vtxz_n24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_n24.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3537_r11901_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_SC_vtxz_0.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_SC_vtxz_0.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_0.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3538_r11902_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_SC_vtxz_p24.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_SC_vtxz_p24.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_p24.out
Queue 1
Arguments = false TrackingEfficiency hijing_300 0 true PbPb18 $(sysFlags) 1 1 50000 user.jeouelle.21.2.113.ztrack.300.mc16_5TeV.PbPb.Hijing_Semicentral_Flow.361106.Zee.recon.AOD.e4916_s3539_r11903_myOutput.root /atlasgpfs01/usatlas/data/jeff/ZTrackAnalysis/data/hijing_300/PbPbEventWeightsFile.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb18_Zee_Hijing_SC_vtxz_p64.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb18_Zee_Hijing_SC_vtxz_p64.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb18_Zee_Hijing_SC_vtxz_p64.out
Queue 1
