Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/bin/run
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run
accounting_group = group_atlas.boulder

dataFlag = data_dvp_000
systematicFlags = false false false false false false false false

#Arguments = false TagAndProbe $(dataFlag) 0 false PbPb15 $(systematicFlags)
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb15.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb15.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb15.out
#Queue 1

Arguments = false TagAndProbe $(dataFlag) 340644 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340644.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340644.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340644.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340683 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340683.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340683.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340683.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340697 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340697.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340697.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340697.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340718 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340718.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340718.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340718.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340814 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340814.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340814.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340814.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340849 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340849.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340849.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340849.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340850 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340850.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340850.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340850.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340910 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340910.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340910.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340910.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340925 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340925.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340925.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340925.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 340973 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/340973.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/340973.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/340973.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 341027 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/341027.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/341027.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/341027.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 341123 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/341123.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/341123.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/341123.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 341184 false pp17 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/341184.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/341184.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/341184.out
Queue 1



Arguments = false TagAndProbe $(dataFlag) 365502 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365502.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365502.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365502.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365512 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365512.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365512.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365512.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365573 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365573.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365573.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365573.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365602 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365602.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365602.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365602.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365627 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365627.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365627.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365627.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365678 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365678.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365678.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365678.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365681 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365681.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365681.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365681.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365709 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365709.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365709.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365709.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365752 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365752.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365752.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365752.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365834 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365834.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365834.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365834.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365914 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365914.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365914.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365914.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 365932 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/365932.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/365932.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/365932.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366011 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366011.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366011.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366011.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366029 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366029.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366029.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366029.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366092 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366092.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366092.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366092.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366142 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366142.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366142.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366142.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366268 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366268.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366268.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366268.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366337 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366337.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366337.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366337.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366383 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366383.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366383.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366383.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366413 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366413.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366413.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366413.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366476 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366476.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366476.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366476.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366526 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366526.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366526.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366526.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366528 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366528.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366528.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366528.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366627 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366627.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366627.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366627.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366691 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366691.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366691.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366691.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366754 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366754.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366754.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366754.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366805 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366805.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366805.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366805.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366860 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366860.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366860.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366860.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366878 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366878.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366878.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366878.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366919 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366919.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366919.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366919.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366931 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366931.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366931.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366931.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 366994 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/366994.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/366994.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/366994.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367023 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367023.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367023.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367023.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367099 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367099.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367099.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367099.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367134 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367134.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367134.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367134.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367165 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367165.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367165.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367165.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367170 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367170.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367170.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367170.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367233 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367233.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367233.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367233.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367273 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367273.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367273.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367273.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367318 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367318.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367318.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367318.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367321 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367321.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367321.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367321.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367363 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367363.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367363.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367363.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367364 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367364.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367364.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367364.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367365 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367365.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367365.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367365.out
Queue 1

Arguments = false TagAndProbe $(dataFlag) 367384 false PbPb18 $(systematicFlags)
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/367384.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/367384.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/367384.out
Queue 1




Arguments = false TagAndProbe mc_dvp_000 0 true pp17 $(systematicFlags) 1 1000000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.pp.361106.Zee.recon.AOD.e4916_s3238_r10313_r10210_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/pp_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/pp_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/pp_Zee.out
Queue 1
Arguments = false TagAndProbe mc_dvp_000 0 true pp17 $(systematicFlags) 1 3360000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.pp.361107.Zmumu.recon.AOD.e4916_s3238_r10313_r10726_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/pp_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/pp_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/pp_Zmumu.out
Queue 1




Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 370000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.361107.pp_Zmumu.recon.AOD.e4916_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pp_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pp_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pp_Zmumu.out
Queue 1
Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 580000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.420067.pn_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pn_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pn_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pn_Zmumu.out
Queue 1
Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 580000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.420068.np_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_np_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_np_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_np_Zmumu.out
Queue 1
Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 869000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.420069.nn_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_nn_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_nn_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_nn_Zmumu.out
Queue 1

Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 430000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.361106.pp_Zee.recon.AOD.e4916_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pp_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pp_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pp_Zee.out
Queue 1
Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 660000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.420121.pn_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pn_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pn_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pn_Zee.out
Queue 1
Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 658000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.420122.np_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_np_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_np_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_np_Zee.out
Queue 1
Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 1010000 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.420123.nn_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_nn_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_nn_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_nn_Zee.out
Queue 1




#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.1793 370000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420090.pp_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pp_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pp_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pp_Zmumu_ptmin25.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.17947 580000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420070.pn_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pn_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pn_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pn_Zmumu_ptmin25.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.17991 580000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420071.np_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_np_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_np_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_np_Zmumu_ptmin25.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.17981 870000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420072.nn_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_nn_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_nn_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_nn_Zmumu_ptmin25.out
#Queue 1
#
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.1793 430000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420127.pp_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pp_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pp_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pp_Zee_ptmin25.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.17947 660000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420124.pn_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pn_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pn_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pn_Zee_ptmin25.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.17991 660000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420125.np_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_np_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_np_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_np_Zee_ptmin25.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.17981 1010000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420126.nn_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_nn_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_nn_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_nn_Zee_ptmin25.out
#Queue 1
#
#
#
#
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.36778 370000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420293.pp_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pp_Zmumu_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pp_Zmumu_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pp_Zmumu_ygt175.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.37302 580000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420290.pn_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pn_Zmumu_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pn_Zmumu_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pn_Zmumu_ygt175.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.37258 580000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420291.np_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_np_Zmumu_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_np_Zmumu_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_np_Zmumu_ygt175.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.37872 870000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420292.nn_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_nn_Zmumu_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_nn_Zmumu_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_nn_Zmumu_ygt175.out
#Queue 1
#
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.36778 430000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420297.pp_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pp_Zee_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pp_Zee_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pp_Zee_ygt175.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.37292 660000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420294.pn_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pn_Zee_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pn_Zee_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pn_Zee_ygt175.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.37264 660000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420295.np_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_np_Zee_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_np_Zee_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_np_Zee_ygt175.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 0.37864 1010000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420296.nn_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_nn_Zee_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_nn_Zee_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_nn_Zee_ygt175.out
#Queue 1




#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 1 1360000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420076.Sherpa.Zmumu_ptmin25.recon.AOD.e6047_d1521_r11472_r11217
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_Sherpa_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_Sherpa_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_Sherpa_Zmumu_ptmin25.out
#Queue 1
#Arguments = false TagAndProbe mc_036 0 true PbPb18 $(systematicFlags) 1 1800000 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.420074.Sherpa.Zee_ptmin25.recon.AOD.e6047_d1521_r11472_r11217
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_Sherpa_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_Sherpa_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_Sherpa_Zee_ptmin25.out
#Queue 1




# background samples, ttbar & Ztautau
Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 0.54439 67734 user.jeouelle.21.2.82.ztrack.036.mc16_5TeV.PbPb.410000.ttbar.recon.AOD.e4917_d1521_r11472_r11217_myOutput.root 
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pp_ttbar.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pp_ttbar.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pp_ttbar.out
Queue 1
Arguments = false TagAndProbe mc_dvp_000 0 true PbPb18 $(systematicFlags) 1 193395 user.dvp.21.2.82.ztrack.000.mc16_5TeV.PbPb.361108.pp_Ztautau.recon.AOD.e4916_d1521_r11472_r11217_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/errors/PbPb_pp_Ztautau.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/logs/PbPb_pp_Ztautau.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZTrackAnalyzer/run/outputs/PbPb_pp_Ztautau.out
Queue 1
