Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/bin/run.exe
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run
accounting_group = group_atlas.boulder

sysFlags = false false false false false false false false



Arguments = false TruthTreeMaker mc_200 0 true pp17 $(sysFlags) 642.820 1 1000000 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.pp.361106.Zee.recon.AOD.e4916_s3238_r10313_r10210_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/pp_Zee.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/pp_Zee.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/pp_Zee.out
Queue 1
Arguments = false TruthTreeMaker mc_200 0 true pp17 $(sysFlags) 642.850 1 3360000 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.pp.361107.Zmumu.recon.AOD.e4916_s3238_r10313_r10726_myOutput.root
Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/pp_Zmumu.err
Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/pp_Zmumu.log
Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/pp_Zmumu.out
Queue 1




#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 642.830 1 357861 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.361107.pp_Zmumu.recon.AOD.e4916_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pp_Zmumu.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pp_Zmumu.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pp_Zmumu.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.520 0.99997 541661 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420067.pn_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pn_Zmumu.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pn_Zmumu.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pn_Zmumu.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.450 0.99996 561006 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420068.np_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_np_Zmumu.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_np_Zmumu.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_np_Zmumu.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 665.320 0.99995 840470 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420069.nn_Zmumu.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_nn_Zmumu.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_nn_Zmumu.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_nn_Zmumu.out
#Queue 1
#
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 642.830 1 415887 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.361106.pp_Zee.recon.AOD.e4916_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pp_Zee.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pp_Zee.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pp_Zee.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.580 0.99997 638346 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420121.pn_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pn_Zee.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pn_Zee.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pn_Zee.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.430 0.99997 638321 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420122.np_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_np_Zee.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_np_Zee.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_np_Zee.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 665.300 0.99994 976912 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420123.nn_Zee.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_nn_Zee.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_nn_Zee.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_nn_Zee.out
#Queue 1
#
#
#
#
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 642.830 0.1793 357894 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420090.pp_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pp_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pp_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pp_Zmumu_ptmin25.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.510 0.17947 560953 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420070.pn_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pn_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pn_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pn_Zmumu_ptmin25.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.480 0.17991 560953 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420071.np_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_np_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_np_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_np_Zmumu_ptmin25.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 665.340 0.17981 841487 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420072.nn_Zmumu_ptmin25.recon.AOD.e5247_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_nn_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_nn_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_nn_Zmumu_ptmin25.out
#Queue 1
#
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 642.830 0.1793 415862 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420127.pp_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pp_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pp_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pp_Zee_ptmin25.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.580 0.17947 638366 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420124.pn_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pn_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pn_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pn_Zee_ptmin25.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.430 0.17991 638366 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420125.np_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_np_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_np_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_np_Zee_ptmin25.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 665.300 0.17981 976816 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420126.nn_Zee_ptmin25.recon.AOD.e5883_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_nn_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_nn_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_nn_Zee_ptmin25.out
#Queue 1
#
#
#
#
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 642.810 0.36736 357900 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420293.pp_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pp_Zmumu_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pp_Zmumu_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pp_Zmumu_ygt175.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.500 0.37292 560051 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420290.pn_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pn_Zmumu_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pn_Zmumu_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pn_Zmumu_ygt175.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.510 0.37264 561091 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420291.np_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_np_Zmumu_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_np_Zmumu_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_np_Zmumu_ygt175.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 665.370 0.37864 839951 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420292.nn_Zmumu_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_nn_Zmumu_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_nn_Zmumu_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_nn_Zmumu_ygt175.out
#Queue 1
#
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 642.830 0.36778 415862 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420297.pp_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pp_Zee_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pp_Zee_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pp_Zee_ygt175.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.520 0.37302 638366 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420294.pn_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pn_Zee_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pn_Zee_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pn_Zee_ygt175.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 656.500 0.37264 637401 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420295.np_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_np_Zee_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_np_Zee_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_np_Zee_ygt175.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 665.350 0.37864 976816 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420296.nn_Zee_ygt175.recon.AOD.e7636_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_nn_Zee_ygt175.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_nn_Zee_ygt175.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_nn_Zee_ygt175.out
#Queue 1




## alternate generator (Sherpa) samples
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 108.750 1 1360000 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420076.Sherpa.Zmumu_ptmin25.recon.AOD.e6047_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_Sherpa_Zmumu_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_Sherpa_Zmumu_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_Sherpa_Zmumu_ptmin25.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 108.660 1 1800000 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.420074.Sherpa.Zee_ptmin25.recon.AOD.e6047_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_Sherpa_Zee_ptmin25.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_Sherpa_Zee_ptmin25.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_Sherpa_Zee_ptmin25.out
#Queue 1




## background samples, ttbar & Ztautau
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 56.695 0.54439 67734 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.410000.ttbar.recon.AOD.e4917_d1521_r11472_r11217_myOutput.root 
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pp_ttbar.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pp_ttbar.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pp_ttbar.out
#Queue 1
#Arguments = false TruthTreeMaker mc_200 0 true PbPb18 $(sysFlags) 642.930 1 193395 user.jeouelle.21.2.113.ztrack.210.mc16_5TeV.PbPb.361108.pp_Ztautau.recon.AOD.e4916_d1521_r11472_r11217_myOutput.root
#Error = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/errors/PbPb_pp_Ztautau.err
#Log = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/logs/PbPb_pp_Ztautau.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/ZHadronAnalysis/Analysis/run/outputs/PbPb_pp_Ztautau.out
#Queue 1
